const $=s=>document.querySelector(s);
const destination=$('#destination'),searchBtn=$('#searchBtn'),locateBtn=$('#locateBtn');
const statusEl=$('#status'),spotsEl=$('#spots'),countEl=$('#count'),summary=$('#summary');
const routesEl=$('#routes'),routeChoicesEl=$('#routeChoices'),routeCountEl=$('#routeCount');
let current=null,watchId=null,route=null,routeLayer=null,currentMarker=null,destMarker=null,saMarkers=[],cached=[],routeOptions=[];
const TOKYO=[35.681236,139.767125];
const map=L.map('map').setView(TOKYO,6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const status=t=>statusEl.textContent=t;const time=d=>d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});const dur=s=>{const m=Math.max(0,Math.round(s/60));return `${Math.floor(m/60)}時間${m%60}分`;};
function hav(a,b){const R=6371000,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p,x=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
function cum(cs){const a=[0];for(let i=1;i<cs.length;i++)a.push(a[i-1]+hav([cs[i-1][1],cs[i-1][0]],[cs[i][1],cs[i][0]]));return a;}
function nearestOnRoute(rt,lat,lon){let best={i:0,d:Infinity};rt.geometry.coordinates.forEach((c,i)=>{const d=hav([lat,lon],[c[1],c[0]]);if(d<best.d)best={i,d};});return best;}
function bearing(a,b){const p=Math.PI/180,y1=a[0]*p,y2=b[0]*p,dl=(b[1]-a[1])*p,y=Math.sin(dl)*Math.cos(y2),x=Math.cos(y1)*Math.sin(y2)-Math.sin(y1)*Math.cos(y2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360;}
function angleDiff(a,b){return Math.abs(((a-b+540)%360)-180);}function routeBearing(rt,i){const cs=rt.geometry.coordinates,a=cs[Math.max(0,i-2)],b=cs[Math.min(cs.length-1,i+2)];return a&&b?bearing([a[1],a[0]],[b[1],b[0]]):0;}
function bearingToTokyo(rt,i){const c=rt.geometry.coordinates[i];return bearing([c[1],c[0]],TOKYO);}
function directionMatches(label,rt,i){const up=/上り|東京方面|都心方面|内回り/i.test(label),down=/下り|地方方面|外回り/i.test(label);if(!up&&!down)return true;if(!current)return true;const ref=Number.isFinite(current.heading)&&current.speed>3?current.heading:routeBearing(rt,i);if(up)return angleDiff(ref,bearingToTokyo(rt,i))<110;if(down)return angleDiff(ref,bearingToTokyo(rt,i))>=70;return true;}
function gps(){if(!navigator.geolocation)return status('このブラウザではGPSを利用できません。');status('現在地を取得しています…');if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(p=>{current={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,heading:p.coords.heading,speed:p.coords.speed||0};if(!currentMarker)currentMarker=L.marker([current.lat,current.lon]).addTo(map).bindPopup('現在地');else currentMarker.setLatLng([current.lat,current.lon]);if(!route)map.setView([current.lat,current.lon],15);else update();},e=>status(e.code===1?'位置情報の利用を許可してください。':'GPSを取得できませんでした。'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});}

// 駅・施設名はNominatimを先に使い、住所は国土地理院を優先する。
// これにより「館山駅」が館山市の住所代表点に化ける問題を避ける。
async function geocode(q){
  const isPoi=/(駅|インター|IC|空港|港|スタジアム|病院|ホテル|公園|道の駅)/i.test(q);
  const nom='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=8&countrycodes=jp&accept-language=ja&q='+encodeURIComponent(q);
  async function nominatim(){const r=await fetch(nom,{headers:{'Accept':'application/json'}});if(!r.ok)throw Error('目的地検索に失敗しました');const d=await r.json();if(!d.length)throw Error('住所・施設名が見つかりませんでした。');const scored=d.map(x=>{let s=0;const txt=(x.display_name||'')+' '+(x.type||'')+' '+(x.class||'');if(/駅/.test(q)&&(/railway|station|halt|train/i.test(txt)||x.type==='station'))s+=100;if(/IC|インター/.test(q)&&/motorway_junction|motorway/i.test(txt))s+=100;if(x.name&&x.name.replace(/駅$/,'')===q.replace(/駅$/,''))s+=80;if(x.display_name?.startsWith(q))s+=20;return{...x,_score:s};}).sort((a,b)=>b._score-a._score);const x=scored[0];return{lat:+x.lat,lon:+x.lon,label:x.display_name||q};}
  async function gsi(){const r=await fetch('https://msearch.gsi.go.jp/address-search/AddressSearch?q='+encodeURIComponent(q));if(!r.ok)throw Error('住所検索に失敗しました');const d=await r.json();if(!d?.length)throw Error('住所が見つかりませんでした。');const x=d[0];return{lat:+x.geometry.coordinates[1],lon:+x.geometry.coordinates[0],label:x.properties?.title||q};}
  if(isPoi){try{return await nominatim();}catch(e){try{return await gsi();}catch(_){throw e;}}}
  try{return await gsi();}catch(e){return await nominatim();}
}

async function osrm(a,b,extra=''){const u=`https://router.project-osrm.org/route/v1/driving/${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson&steps=true&alternatives=true${extra}`;const r=await fetch(u);if(!r.ok)throw Error('ルートAPIに接続できませんでした');const d=await r.json();if(d.code!=='Ok'||!d.routes?.length)throw Error('ルートが見つかりませんでした');return d.routes;}
async function osrmVia(points,extra=''){const coords=points.map(p=>`${p.lon},${p.lat}`).join(';');const u=`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson&steps=true&alternatives=false&continue_straight=true${extra}`;const r=await fetch(u);if(!r.ok)return null;const d=await r.json();return d.code==='Ok'&&d.routes?.[0]?d.routes[0]:null;}
function motorwayScore(rt){let motorway=0,trunk=0,total=0;for(const leg of rt.legs||[])for(const st of leg.steps||[]){const km=st.distance||0;total+=km;const cls=st.classes||[];if(cls.includes('motorway'))motorway+=km;else if(cls.includes('trunk'))trunk+=km;}return{motorway,trunk,total,ratio:total?(motorway+trunk)/total:0};}
function roadNames(rt){const a=[];for(const leg of rt.legs||[])for(const st of leg.steps||[]){const n=st.name||st.ref;if(n&&!a.includes(n))a.push(n);if(a.length>=5)break;}return a;}
function classifyRoute(rt,i,kind='auto'){const s=motorwayScore(rt);let name=kind==='highway'?'高速優先':kind==='general'?'一般道中心':(s.ratio>=.65?'高速道路中心':s.ratio>=.35?'高速＋一般道':'一般道中心');return{rt,name,tag:i===0?'おすすめ':'別ルート',mins:Math.round(rt.duration/60),km:(rt.distance/1000).toFixed(1),ratio:s.ratio,roads:roadNames(rt).join(' → '),kind};}

async function nearbyHighwayJunctions(p){
  const d=0.55,lat1=p.lat-d,lat2=p.lat+d,lon1=p.lon-d,lon2=p.lon+d;
  const q=`[out:json][timeout:20];node["highway"="motorway_junction"](${lat1},${lon1},${lat2},${lon2});out tags;`;
  const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'text/plain'},body:q});if(!r.ok)return[];const j=await r.json();return(j.elements||[]).map(x=>({lat:x.lat,lon:x.lon,name:x.tags?.name||x.tags?.ref||'IC'})).filter(x=>hav([p.lat,p.lon],[x.lat,x.lon])<55000).sort((a,b)=>hav([p.lat,p.lon],[a.lat,a.lon])-hav([p.lat,p.lon],[b.lat,b.lon])).slice(0,4);}

async function getRoutes(a,b){
  const candidates=[];
  try{(await osrm(a,b)).forEach(r=>candidates.push(classifyRoute(r,candidates.length,'auto')));}catch(e){}
  // 明示的に高速道路へ乗るルートを作る。OSRMの通常検索だけでは一般道が最短になり、高速ルートが返らないことがあるため。
  try{
    const [sj,dj]=await Promise.all([nearbyHighwayJunctions(a),nearbyHighwayJunctions(b)]);
    const pairs=[];for(const s of sj.slice(0,3)){for(const d of dj.slice(0,3)){const score=hav([a.lat,a.lon],[s.lat,s.lon])+hav([b.lat,b.lon],[d.lat,d.lon]);pairs.push({s,d,score});}}
    pairs.sort((x,y)=>x.score-y.score);
    for(const p of pairs.slice(0,3)){const r=await osrmVia([a,p.s,p.d,b]);if(r){const sc=motorwayScore(r);if(sc.ratio>=.18)candidates.push(classifyRoute(r,candidates.length,'highway'));}}
  }catch(e){console.warn('高速ルート生成失敗',e);}
  // 一般道ルートも明示的に1本用意する。
  try{const rr=await osrm(a,b,'&exclude=motorway');if(rr[0])candidates.push(classifyRoute(rr[0],candidates.length,'general'));}catch(e){}
  const unique=[];for(const o of candidates){const dup=unique.some(x=>Math.abs(+x.km-(+o.km))<1&&Math.abs(x.mins-o.mins)<3&&x.kind===o.kind);if(!dup)unique.push(o);} 
  if(!unique.length)throw Error('ルートが見つかりませんでした');
  unique.sort((a,b)=>{const wa=a.kind==='highway'?2:a.kind==='auto'&&a.ratio>.35?1:0;const wb=b.kind==='highway'?2:b.kind==='auto'&&b.ratio>.35?1:0;if(wb!==wa)return wb-wa;return a.mins-b.mins;});
  return unique.slice(0,5);
}
function showRouteChoices(routes){routeOptions=routes;routeCountEl.textContent=routeOptions.length+'ルート';routesEl.classList.remove('hidden');routeChoicesEl.innerHTML=routeOptions.map((o,i)=>`<button class="route-choice ${i===0?'selected':''}" data-index="${i}"><div class="top"><span class="name">${o.name}</span><span class="tag">${o.tag}</span></div><div class="meta"><span>${o.km} km</span><span>${o.mins}分</span><span>高速等 ${Math.round(o.ratio*100)}%</span></div><div class="roads">${o.roads||'経路詳細なし'}</div></button>`).join('');routeChoicesEl.querySelectorAll('.route-choice').forEach(b=>b.onclick=()=>selectRoute(+b.dataset.index));}
async function selectRoute(i){const o=routeOptions[i];if(!o)return;route=o.rt;route.dest=window.__dest;routeOptions.forEach((_,j)=>{const b=routeChoicesEl.querySelector(`[data-index="${j}"]`);if(b)b.classList.toggle('selected',j===i);});status('選択したルートのSA・PAを検索中…');draw();try{cached=await getSpots(route);render(cached);status(`「${o.name}」を選択中。GPSで現在地を自動更新しています。`);}catch(e){status(e.message||'SA・PA検索に失敗しました。');}}
async function getSpots(rt){const cs=rt.geometry.coordinates,lat=cs.map(c=>c[1]),lon=cs.map(c=>c[0]);const s=Math.min(...lat)-.03,n=Math.max(...lat)+.03,w=Math.min(...lon)-.03,e=Math.max(...lon)+.03;const q=`[out:json][timeout:30];nwr["highway"~"^(services|rest_area)$"](${s},${w},${n},${e});out center tags;`;const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'text/plain'},body:q});if(!r.ok)throw Error('SA・PAデータを取得できませんでした');const d=await r.json(),cc=cum(cs),total=cc.at(-1),out=[];const include=/(サービスエリア|パーキングエリア|\bSA\b|\bPA\b|SA・PA|ＳＡ|ＰＡ)/i,exclude=/(道の駅|コインパーキング|駐車場|VIP|ラウンジ|ロータリー|バス停|ガソリンスタンド|サービスステーション)/i;for(const x of d.elements||[]){const la=x.lat??x.center?.lat,lo=x.lon??x.center?.lon;if(la==null||lo==null)continue;const t=x.tags||{},name=t.name||t['name:ja']||'',ja=t['name:ja']||name,label=ja||name;if(!label||exclude.test(label)||(!include.test(name)&&!include.test(ja)))continue;const z=nearestOnRoute(rt,la,lo);if(z.d>120)continue;const km=cc[z.i]/1000;if(km<1||km>total/1000-1)continue;if(current&&Number.isFinite(current.heading)&&current.speed>3&&angleDiff(current.heading,routeBearing(rt,z.i))>75)continue;if(!directionMatches(label,rt,z.i))continue;let type='PA';if(/サービスエリア|\bSA\b|ＳＡ/i.test(label)&&!/パーキングエリア|\bPA\b|ＰＡ/i.test(label))type='SA';if(/SA・PA/i.test(label))type='PA';if(out.some(v=>hav([v.lat,v.lon],[la,lo])<500))continue;out.push({name:label,type,lat:la,lon:lo,km,roadDist:z.d});}return out.sort((a,b)=>a.km-b.km).slice(0,40);}
function draw(){if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.geoJSON(route.geometry,{style:{weight:5}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[15,15]});if(destMarker)map.removeLayer(destMarker);destMarker=L.marker([route.dest.lat,route.dest.lon]).addTo(map).bindPopup(`目的地: ${route.dest.label||'目的地'}`);}
function render(spots){saMarkers.forEach(m=>map.removeLayer(m));saMarkers=[];const now=Date.now(),near=nearestOnRoute(route,current.lat,current.lon),cc=cum(route.geometry.coordinates),passed=cc[near.i],total=cc.at(-1),remain=Math.max(0,total-passed),sec=route.duration*(remain/Math.max(1,total));$('#totalDistance').textContent=(remain/1000).toFixed(1)+' km';$('#eta').textContent=time(new Date(now+sec*1000));$('#remainingTime').textContent=dur(sec);summary.classList.remove('hidden');const active=spots.map(x=>({...x,remaining:Math.max(0,x.km*1000-passed)})).filter(x=>x.remaining>500);spotsEl.innerHTML=active.length?active.map(x=>{const es=sec*(x.remaining/Math.max(1,remain));return`<article class="spot"><div class="badge">${x.type==='SA'?'S':'P'}</div><div><h3>${x.name}</h3><p>${x.type} ・ 到着予定 ${time(new Date(now+es*1000))}</p></div><div class="distance"><strong>${(x.remaining/1000).toFixed(1)} km</strong><span>あと ${dur(es)}</span></div></article>`;}).join(''):`<div class="empty">このルート上で確認できるSA・PAはありません。</div>`;countEl.textContent=active.length+'か所';active.forEach(x=>saMarkers.push(L.marker([x.lat,x.lon]).addTo(map).bindPopup(`${x.name}（${x.type}）`)));}
function update(){if(route&&current)render(cached);}
async function search(){if(!current){status('先に⌖を押して現在地を取得してください。');gps();return;}const q=destination.value.trim();if(!q)return;searchBtn.disabled=true;try{routesEl.classList.add('hidden');status('目的地を正確に検索中…');const to=await geocode(q);window.__dest=to;destination.value=q;status(`目的地: ${to.label}。高速道路を含む複数ルートを検索中…`);const routes=await getRoutes(current,to);showRouteChoices(routes);await selectRoute(0);status(`「${routeOptions[0].name}」を選択中。別ルートもタップで選べます。`);}catch(e){console.error(e);status(e.message||'検索に失敗しました。');}finally{searchBtn.disabled=false;}}
locateBtn.onclick=gps;searchBtn.onclick=search;destination.onkeydown=e=>{if(e.key==='Enter')search();};gps();
